spring.application.name=apiagrosync

spring.datasource.url=jdbc:postgresql://localhost:5432/agrosync
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

spring.security.secret=teste@12546*
spring.security.issuer=agrosync